#' get classic taxonomy table from taxids
#' @param x A dataframe with a column called "taxid".
#' @param taxo An obitools-formatted taxonomy database as an R object, generated by \code{\link[ROBITaxonomy]{read.taxonomy}}.
#' @return The original dataframe \code{x} with seven new taxonomy columns, kingdom to species.
#' @examples
#' get.classic.taxonomy.BAS(My_df_with_taxid_col, my_obitools-formatted_taxonomy_as_object)
#' @export
get.classic.taxonomy.Bas = function(x, obitaxdb) {
  classic.taxo = c("kingdom", "phylum", "class", "order", "family", "genus", "species")
  taxids = x$taxid
  out = as.data.frame(do.call("cbind", lapply(classic.taxo, function(y) {
    ROBITaxonomy::scientificname(obitaxdb, ROBITaxonomy::taxonatrank(obitaxdb,taxids,y))
  })))
  colnames(out) = paste(classic.taxo, "_name_ok", sep="")
  rownames(out) = row.names(x)
  out$scientific_name_ok = ROBITaxonomy::scientificname(obitaxdb, taxids)
  out$taxonomic_rank_ok = ROBITaxonomy::taxonomicrank(obitaxdb, taxids)
  return(out)
}

#' Add taxids to fasta
#' @param infile A fasta file with scientific names in headers.
#' \itemize{
#'     \item By default, the sequence identifier is used.
#'     \itemize{
#'         \item Underscore characters (_) are substituted by spaces.
#'         \item e.g. \code{>Leiopelma_hochstetteri length=658}}
#'     \item Alternatively, the k option specifies an attribute containing the taxon scientific name.
#'     \itemize{
#'         \item e.g.  \code{>seqX species=Leiopelma_hochstetteri;}
#'         \item Note that the \code{space} before the attribute and the \code{;} after is mandatory}}
#' @param taxo An obitools-formatted taxonomy database - a set of files (.adx,.ndx,.rdx,.tdx).
#' @return A new fasta with taxids in header.
#' @note Sequences for which taxids cannot be found are discarded
#' @examples
#' obiaddtaxids.Bas(infile = a, taxo="/media/sf_Documents/WORK/CIBIO/STATS_AND_CODE/TAXONOMIES/obitax_26-4-19",
#' out = "wTaxids.head.test.op2.fasta",k = "species")
#' @export
obiaddtaxids.Bas<-function(infile,taxo,k=NULL,out){
  cb <- function(line, proc) {cat(line, "\n")}
  if(is.null(k)){
    f<-process$new(command = "obiaddtaxids", args=c(infile,"-d",taxo),
                   echo_cmd = T,stdout=out)
    f$wait()
    d<-"SUCCESS!"
  }
  if(!is.null(k)){
    f<-process$new(command = "obiaddtaxids", args=c(infile,"-d",taxo, "-k", k),
                   echo_cmd = T,stdout=out)
    f$wait()
    d<-"SUCCESS!"
  }
  }

#' Report taxonomic resolution attained for each taxon amplified in silico
#' @param ecopcroutput A data frame such as that produced by \code{ecoPCR.Bas}.
#' @param taxo An obitools-formatted taxonomy database. This can be an R object, generated by \code{\link[ROBITaxonomy]{read.taxonomy}}
#'     or \code{\link[bastools]{NCBI2obitaxonomy}}, or a set of files (.adx,.ndx,.rdx,.tdx).
#' @param taxLevel Taxonomic level to use to generate list.
#'     Accepted values are "superkingdom", "phylum", "class", "order", "family", "genus", "species" (default), "subspecies".
#' @return A data frame consisting of the species amplified, the taxid and the taxon resolution attained
#'     by the amplified fragment.
#' @examples
#' a2<-system.file("extdata", "45F-63R_4Mis_ALLVERTS_REFSEQ.ecopcroutput", package = "bastools")
#' b2<-substr(system.file("extdata", "obitax_26-4-19.ndx", package = "bastools"),1,str_locate(system.file("extdata", "obitax_26-4-19.ndx", package = "bastools"),"\\.")-1)
#' d2<-ecopcr.hit.table(a2,obitaxdb = b2,taxLevel = "class")
#' e2<-d2$ecopcroutput_uncleaned
#' test.res2<-ecopcroutput.res.Bas(e2,b2,taxLevel = "order")
#' plot.ecopcroutput.res.Bas(test.res2)
#' @export
#'
ecopcroutput.res.Bas<-function(ecopcroutput,obitaxdb,taxLevel="species"){
  if (class(obitaxdb)[1]!="obitools.taxonomy") obitaxdb2=ROBITaxonomy::read.taxonomy(obitaxdb)
  if (class(obitaxdb)[1]=="obitools.taxonomy") obitaxdb2=obitaxdb
  res=ROBIBarcodes::resolution(taxonomy = obitaxdb2,ecopcr = ecopcroutput)
  a<-as.data.frame(res)
  a$res<-gsub(x = a$res,pattern = "infraclass",replacement = "class")
  a$res<-gsub(x = a$res,pattern = "subfamily",replacement = "family")
  a$res<-gsub(x = a$res,pattern = "tribe",replacement = "family")
  a$res<-gsub(x = a$res,pattern = "suborder",replacement = "order")
  a$res<-gsub(x = a$res,pattern = "infraorder",replacement = "order")
  a$res<-gsub(x = a$res,pattern = "superfamily",replacement = "order")
  a$res<-gsub(x = a$res,pattern = "subclass",replacement = "class")
  a$res<-gsub(x = a$res,pattern = "subgenus",replacement = "genus")
  a$res<-gsub(x = a$res,pattern = "species subgroup",replacement = "species")
  a$res<-gsub(x = a$res,pattern = "cohort",replacement = "order")

  #K,P,C,O,F,G,S

  b<-cbind(ecopcroutput,a)

  taxongroup=paste0(taxLevel,"_name")
  e<-as.data.frame(table(b[,taxongroup],b$res))
  colnames(e)<-c("taxon","resolution","Freq")
  f<-e[e$Freq!=0,]
  return(f)
}

#' @export
obiaddtaxids.nodump.Bas<-function(infile,taxo,k=NULL,out){
  cb <- function(line, proc) {cat(line, "\n")}
  if(is.null(k)){
    f<-process$new(command = "obiaddtaxids", args=c(infile,"-d",taxo),
                   echo_cmd = T,stdout=out)
    f$wait()
    d<-"SUCCESS!"
  }
  if(!is.null(k)){
    f<-process$new(command = "obiaddtaxids", args=c(infile,"-d",taxo, "-k", k),
                   echo_cmd = T,stdout=out)
    f$wait()
    d<-"SUCCESS!"
  }
}

