---
title: "Processing a taxatable post MBC and illumina_post_MBC_script2.R"
html_notebook: default
subtitle: ''
classoption: portrait
output: html_document
fig_crop: no
fig_width: 6 
fig_height: 4 

---
## things this script should do  

```{r, eval=TRUE, results='hide'}
#load taxatable(s)
#load single mastersheet
#subset the mastersheet if desired
##if using subset mastersheet, use only subset taxatable (or merged taxatable if >1 supplied)
#show summary: taxa list, sum of reads, min and max reads in a sample, no. samples


```

## settings 
```{r, eval=TRUE}
#if multiple, will be merged
taxatabs<-c("/mnt/Disk1/BASTIAN_POST_MBC_MISEQS/FILTURB_12S_BLAST/FILTURB-2018_07_12S.none.flash2.vsearch_qfilt.cutadapt.vsearch_uniq.vsearch_afilt.allsamples_step5.ALL_vsearch_uniq.nodenoise.noclust.taxatable.tf.spliced.txt")

#filturb datasheet
ss_url<-"https://docs.google.com/spreadsheets/d/1FUSaeVaYzms2EOGUoCAB4jaRKzguD3AKTsC8lYwaKP4/edit?ts=5dae01be#gid=1531090624"

#options for subsetting master sheet 
subsetlist<-list(experiment_id=c("2018_07"), Primer_set=c("12SV5.2"),study=c("South"))

bastoolsDir<-"/home/bastian.egeter/git_bastools/bastools/"

#sample_type for "real" samples (not negatives)
real=c("Field")

#columns in master sheet to make barplots of
columns=c("biomaterial","sample_type","Site")

#print taxon tables for negatives (even if not printed, plots will still be made)
printnegs=F

#print taxon tables for removal of contaminants
printcontaminations=F

#group code to remove contaminants based on negatives. e.g. for water field negatives, group code is probably site or something similar. For extraction negatives it is probably extraction batch etc. This should be improved to handle multiple codes
group.code="Site"

```

## load functions
```{r, eval=TRUE, results='hide'}
setwd(bastoolsDir)
source("master_functions.R")
library(ggplot2)
library(googlesheets4)
sheets_auth(email = "basegeter@gmail.com")
options(httr_oob_default = TRUE)
```

## organise mastersheet
```{r, eval=TRUE,echo=F}
master_sheet<-google.read.master.url(ss_url)

#check on number of samples in each category
message("Showing xtabs for entire datasheet, including Sample_Type by default")
master_xtabs(master_sheet,columns=c("sample_type",names(subsetlist)))

#subset master sheet for this study
message("Subsetting datasheet, check output to see if it made sense")
ms_ss<-subset_mastersheet(master_sheet, subsetlist)

#check again to see the subset made sense
master_xtabs(ms_ss,columns=c("sample_type",names(subsetlist)))
```

## import taxtabs and subset
```{r, eval=TRUE,echo=F}
#import taxtabs
all.taxatabs<-bas.merge.taxatabs(taxatabs)
```

## make new taxa table based on subsetted master sheet
```{r, eval=TRUE,echo=F}
all.taxatabs.ss<-cbind(taxon=all.taxatabs$taxon,all.taxatabs[colnames(all.taxatabs) %in% ms_ss$ss_sample_id])

message("Removing taxa/samples with 0 reads")
all.taxatabs.ss<-rm.0readtaxSam(all.taxatabs.ss)

#summary
message("Showing summary of detections")
a<-summary.dxns.by.taxon(all.taxatabs.ss)
DT::datatable(a, rownames = FALSE, options = list(pageLength = 50, scrollX=T))

taxatab.pieplot(all.taxatabs.ss)
```



## remove the NAs and no_hits
```{r, eval=TRUE,echo=F}
count1<-sum(all.taxatabs.ss[,-1])
all.taxatabs.ss<-all.taxatabs.ss[all.taxatabs.ss$taxon!="NA;NA;NA;NA;NA;NA;NA",]
count2<-sum(all.taxatabs.ss[,-1])
message(paste(count1-count2, "'NA' reads removed"))
all.taxatabs.ss<-all.taxatabs.ss[all.taxatabs.ss$taxon!="no_hits;no_hits;no_hits;no_hits;no_hits;no_hits;no_hits",]
count3<-sum(all.taxatabs.ss[,-1])
message(paste(count2-count3, "'No_hits' reads removed"))

taxatab.pieplot(all.taxatabs.ss,hidelegend = T)
```

## reads & dxns by rank
```{r, eval=TRUE,echo=F}
reads.by.rank(all.taxatabs.ss)
dxns.by.rank(all.taxatabs.ss)
```

## detection distribution
```{r, eval=TRUE,echo=F}
long<-reshape2::melt(all.taxatabs.ss)
long$reads<-long$value
long<-long[long$value>0,]
ggplot(long, aes(x=reads)) + geom_histogram() +theme(legend.position = "none") 

long2<-long[long$value<500,]
ggplot(long2, aes(x=reads)) + geom_histogram(binwidth = 20)
```

## krona plot
```{r, echo=FALSE,results="asis"}
#bas.krona.plot(taxatabs,KronaPath = "/home/bastian.egeter/Tools/Krona.install/bin/ktImportText")
#htmltools::includeHTML("/mnt/Disk1/BASTIAN_POST_MBC_MISEQS/FILTURB_12S_BLAST/FILTURB-2018_07_12S.none.flash2.vsearch_qfilt.cutadapt.vsearch_uniq.vsearch_afilt.allsamples_step5.ALL_vsearch_uniq.nodenoise.noclust.taxatable.tf.spliced.krona.html")

#shiny::includeHTML("/mnt/Disk1/BASTIAN_POST_MBC_MISEQS/FILTURB_12S_BLAST/FILTURB-2018_07_12S.none.flash2.vsearch_qfilt.cutadapt.vsearch_uniq.vsearch_afilt.allsamples_step5.ALL_vsearch_uniq.nodenoise.noclust.taxatable.tf.spliced.krona.html")

xfun::embed_file("/mnt/Disk1/BASTIAN_POST_MBC_MISEQS/FILTURB_12S_BLAST/FILTURB-2018_07_12S.none.flash2.vsearch_qfilt.cutadapt.vsearch_uniq.vsearch_afilt.allsamples_step5.ALL_vsearch_uniq.nodenoise.noclust.taxatable.tf.spliced.krona.html")
```

## stack plots (select top 30 taxa?)
```{r, eval=TRUE,echo=F}
message("Plotting taxatable according to selected master sheet columns, values=reads, plotted as %")
for(i in 1:length(columns)){
  a<-taxatab.stackplot(all.taxatabs.ss,master_sheet = ms_ss,column = columns[i],as.percent = T,as.dxns = F,hidelegend = T)
  print(a[[1]])
}

print(a[[2]])

message("Plotting taxatable according to selected master sheet columns, values=reads, plotted as raw")
for(i in 1:length(columns)){
  a<-taxatab.stackplot(all.taxatabs.ss,master_sheet = ms_ss,column = columns[i],as.percent = T,as.dxns = F,hidelegend = T)
  print(a[[1]])
}

print(a[[2]])

message("Plotting taxatable according to selected master sheet columns, values=detections,plotted as raw")
for(i in 1:length(columns)){
  a<-taxatab.stackplot(all.taxatabs.ss,master_sheet = ms_ss,column = columns[i],as.percent = F,as.dxns = T,hidelegend = T)
  print(a[[1]])
}

print(a[[2]])

```


## check negatives
```{r, eval=TRUE,echo=F}
#check negatives
if(printnegs==F) message("Hiding tabular output of negatives")

negatives<-negs.stats(taxatab=all.taxatabs.ss,ms_ss = ms_ss,real=real,ex_hominidae=F,printnegs = printnegs)

for(i in 1:length(negatives)){
  message(paste("Plotting", names(negatives)[i]))
  if(length(negatives[[i]])>0) print(taxatab.stackplot(negatives[[i]]))
}
```

## test removing contaminants blindly
```{r, eval=TRUE,echo=F}
#just to look:
all.taxatabs.ss.rmcons<-remove.contaminant.taxa(taxatab = all.taxatabs.ss,master_sheet = ms_ss,negatives = negatives,group.code = group.code,printcontaminations = printcontaminations)
#note - if I have PCR or extraction negs, need to think about the group carefully

```

