#' Make tables of hit counts from ecoPCR results divided by taxonomic level and no. of primer mismatches and compare against original database
#' @title Process ecoPCR output files into hit tables
#' @param ecopcrhits The output from running an ecoPCR bash command. This can be a file or a datatable produced by
#'     \code{\link[ROBIBarcodes]{read.ecopcr.result}}. The latter performs faster.
#' @param obitaxdb An obitools-formatted taxonomy database. This can be a set of files (.adx,.ndx,.rdx,.tdx) or
#'     a pre-loaded taxonomy in R (produced by \code{\link[ROBITaxonomy]{read.taxonomy}}). The latter performs faster.
#' @param ecopcrdb.tab Optional. The ecoPCR database that was used during the ecoPCR command, in tab format, generated by the obitab command.
#' @param taxLevel Taxonomic level to use to make hit table. Accepted values are "kingdom", "phylum", "class", "order", "family", "genus", "species".
#'
#' @return Default: A list containing the following dataframes
#' \itemize{
#'     \item \code{ecopcroutput_uncleaned}: An uncleaned version of \code{ecopcroutput_file} containing duplicate species
#'     \item \code{ecopcroutput_clean}: A clean version of \code{ecopcroutput_file} with duplicate species removed and taxonomy added
#'     \item \code{ecopcrdb_clean}: A clean version of \code{ecopcrdb.tab} with duplicate species removed, taxonomy added
#'         and a logical TRUE/FALSE column of whether the species was amplified
#'     \item \code{HT}: A Hit Table (no. of species amplified), arranged by taxonomic class and no. of primer mismatches
#'     \item \code{HT_PC}: A Hit Table indicating the percentage of species amplified from original database,
#'         arranged by taxonomic class and no. of primer mismatches
#' }
#'     If \code{ecopcrdb.tab} is not provided, only \code{ecopcroutput_uncleaned}, \code{ecopcroutput_clean}
#'     and \code{HT} are returned.
#'         If the \code{out} option is set to something other than default, only the corresponding dataframe is returned.
#'
#'@note Currently has in-built setting to find certain orders and give them the class "Reptilia", as this missing info
#'    was causing trouble in earlier versions.
#'    The function involves removing duplicate species from the input \code{ecopcrhits}. In cases where a species has more than one hit,
#'    the hit with the lowest no. of primer mismatches is kept.
#'    Comparing ecoPCR results against the original database only makes sense if all the sequences in the original database contained the primer binding sites.
#'@examples
#' ecopcrTidyAll<-ecopcr.hit.table("C:/Users/basti/Documents/WORK/CIBIO/AA_PROJECTS/MINION/45F-63R_4Mis_ALLVERTS_REFSEQ.ecopcroutput",
#'
#'@export
clean.ecopcrhits<- function(ecopcrhits,ecopcrdb.tab=NULL){
  ######add a check if ecopcr contains results before running

  #import and clean ecopcroutput
  message("Reading ecopcr results...")
  if (class(ecopcrhits)=="data.frame") ecopcroutput<-ecopcrhits
  if (class(ecopcrhits)!="data.frame") ecopcroutput=ROBIBarcodes::read.ecopcr.result(ecopcrhits)
  message(c("Total of ",length(ecopcroutput$AC)," hits"))

  message("Removing duplicate species hits...this can happen because multiple primer binding sites were found for one
          species. Here, the hit with the lowest no. of total mismatches is kept")
  #cleaning (i.e. pick one entry per species, based on lowest mismatches)
  ecopcroutput$total_mismatches<-as.numeric(ecopcroutput$forward_mismatch)+as.numeric(ecopcroutput$reverse_mismatch)
  ecopcroutput2 <- ecopcroutput[order(ecopcroutput$species_name,ecopcroutput$total_mismatches), ]
  ecopcroutput2<-ecopcroutput2[!duplicated(ecopcroutput2$species_name),]
  message(c("Total of ",length(ecopcroutput2$AC), " unique species"))

  ##add taxonomy
  message("Adding taxonomy...")
  pathToTaxonomyDB<-gsub(pattern = "config.txt",replacement = "obitax_26-4-19",
                         x = system.file("extdata", "config.txt", package = "bastools"))

  obitaxdb2=ROBITaxonomy::read.taxonomy(pathToTaxonomyDB)
  taxon.table=get.classic.taxonomy.Bas(ecopcroutput2,obitaxdb2)
  taxon.table$class_name_ok<-as.character(taxon.table$class_name_ok)
  taxon.table$order_name_ok<-as.character(taxon.table$order_name_ok)
  taxon.table$order_name<-ifelse(is.na(taxon.table$order_name_ok),"empty",taxon.table$order_name_ok)
  ecopcroutput2$class_name<-taxon.table$class_name_ok
  ecopcroutput2$order_name<-taxon.table$order_name_ok
  ecopcroutput2$phylum_name<-taxon.table$phylum_name_ok
  ecopcroutput2$kingdom_name<-taxon.table$kingdom_name_ok
  return(ecopcroutput2)
}

clean.ecopcrhits2<- function(ecopcrhits,ecopcrdb,obitaxoR){
  message("sometimes, when a seq only had family-level taxonomy, ecopcr was not conducted, we get an empty row...")
  message("not sure why, removing from originaldb and ecopcr results")
          if(length(ecopcrdb$id)!=length(unique(ecopcrdb$id))) stop("ecopcrdb ids must be unique and must match ecopcrhits ids")
          seqid<-ecopcrhits[is.na(ecopcrhits$forward_mismatch),"AC"]
          ecopcrdb<-ecopcrdb[!ecopcrdb$id %in% seqid,]
          ecopcrhits<-ecopcrhits[!is.na(ecopcrhits$forward_mismatch),]

          message("Removing duplicate hits...this can happen because multiple primer binding sites were found for one
          sequence. Here, the hit with the lowest no. of total mismatches is kept.")
          #cleaning (i.e. pick one entry per seqid, based on lowest mismatches)
          ecopcrhits$total_mismatches<-as.numeric(ecopcrhits$forward_mismatch)+as.numeric(ecopcrhits$reverse_mismatch)
          ecopcrhits <- ecopcrhits[order(ecopcrhits$AC,ecopcrhits$total_mismatches), ]
          ecopcrhits<-ecopcrhits[!duplicated(ecopcrhits$AC),]
          message(c("Total of ",length(ecopcrhits$AC), " unique hits"))

          ##add taxonomy
          message("Adding taxonomy...")
          taxon.table=get.classic.taxonomy.Bas(ecopcrhits,obitaxoR)
          taxon.table$class_name_ok<-as.character(taxon.table$class_name_ok)
          taxon.table$order_name_ok<-as.character(taxon.table$order_name_ok)
          taxon.table$order_name<-ifelse(is.na(taxon.table$order_name_ok),"NA",taxon.table$order_name_ok)

          ecopcrhits$class_name<-taxon.table$class_name_ok
          ecopcrhits$order_name<-taxon.table$order_name_ok
          ecopcrhits$phylum_name<-taxon.table$phylum_name_ok
          ecopcrhits$kingdom_name<-taxon.table$kingdom_name_ok

          #remove useless cols and reorder
          ecopcrhits$forward_tm=NULL
          ecopcrhits$reverse_tm=NULL
          ecopcrhits<-ecopcrhits[,c(1:10,23,22,24,25,11:21)]

          a<-list(ecopcrdb,ecopcrhits)
          return(a)
}

add.stats.taxlevel<-function(ecopcrhits,levelofinterest,Pf,Pr,obitaxoR){
  #derep by taxonomic level of interest
  hitsdr<-ecohitsDerepByLevel(ecopcrhits = ecopcrhits,levelofinterest = levelofinterest)

  #add 3' mismatches to ecopcroutput - half-primer
  f_mismatch_table<-mismatch.table(hitsdr,primer.seq = Pf,primer.direction = "f")
  f_mismatches_3prime<-as.data.frame(rowSums(f_mismatch_table[,as.integer(nchar(Pf)/2):nchar(Pf)]))
  colnames(f_mismatches_3prime)<-"f_mms_3pHalf"
  r_mismatch_table<-mismatch.table(hitsdr,primer.seq = Pr, primer.direction = "r")
  r_mismatches_3prime<-as.data.frame(rowSums(r_mismatch_table[,as.integer(nchar(Pr)/2):nchar(Pr)]))
  colnames(r_mismatches_3prime)<-"r_mms_3pHalf"
  hitsdr2<-cbind(hitsdr,f_mismatches_3prime,r_mismatches_3prime)

  #add 3' mismatches to ecopcroutput - 6bp
  f_mismatches_3prime6<-as.data.frame(rowSums(f_mismatch_table[,as.integer(nchar(Pf)-5):nchar(Pf)]))
  colnames(f_mismatches_3prime6)<-"f_mms_3p6bp"
  r_mismatches_3prime6<-as.data.frame(rowSums(r_mismatch_table[,as.integer(nchar(Pr)-5):nchar(Pr)]))
  colnames(r_mismatches_3prime6)<-"r_mms_3p6bp"
  hitsdr3<-cbind(hitsdr2,f_mismatches_3prime6,r_mismatches_3prime6)

  #add Tms -3 prime half
  hitsdr3$f_Tm_3pHalf<-Tm.calc(substr(x = hitsdr3$forward_match,
                                      start = as.integer(nchar(as.character(hitsdr3$forward_match))/2+1),
                                      stop = nchar(as.character(hitsdr3$forward_match))))
  hitsdr3$r_Tm_3pHalf<-Tm.calc(substr(x = hitsdr3$reverse_match,
                                      start = as.integer(nchar(as.character(hitsdr3$reverse_match))/2+1),
                                      stop = nchar(as.character(hitsdr3$reverse_match))))
  #add Tms -3 prime 6bp
  hitsdr3$f_Tm_3p6bp<-Tm.calc(substr(x = hitsdr3$forward_match,
                                     start = as.integer(nchar(as.character(hitsdr3$forward_match))-5),
                                     stop = nchar(as.character(hitsdr3$forward_match))))
  hitsdr3$r_Tm_3p6bp<-Tm.calc(substr(x = hitsdr3$reverse_match,
                                     start = as.integer(nchar(as.character(hitsdr3$reverse_match))-5),
                                     stop = nchar(as.character(hitsdr3$reverse_match))))

  #add taxonomic resolution
  hitsdr4<-add.res.Bas(ecopcroutput = hitsdr3,obitaxdb = obitaxoR) #####needs work!!
}
